---
title: "MetaPR2 - Figures"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


# Initialize

```{r init, echo=TRUE, message=FALSE, warning=FALSE}
source(here::here("R", "init.R"))
```

# Figures

## V9 Select V4 only

```{r}
asv_set_V9 <- list()

asv_set_V9$df <- asv_set$df %>% 
  dplyr::filter(gene_region == "V9", 
                DNA_RNA == "DNA")

n_reads_pct_V9 <- sum(asv_set_V9$df$n_reads_pct)
n_reads_V9 <- sum(asv_set_V9$df$n_reads)

samples_V9 <- asv_set_V9$df %>% 
  pull("file_code") %>% 
  unique()

n_samples_V9 <- length(samples_V9)
  
asv_code_V9 <- asv_set_V9$df %>% 
  dplyr::filter(gene_region == "V9", 
                DNA_RNA == "DNA") %>% 
  pull("asv_code") %>% 
  unique()

asv_set_V9$fasta <- asv_set$fasta %>% 
  filter(asv_code %in% asv_code_V9)

n_asvs_V9 <- nrow(asv_set_V9$fasta)

cat("Total numbers of V9 samples: ",n_samples_V9, "\n")
cat("Total numbers of V9 ASVs: ",n_asvs_V9 , "\n")
cat("Total numbers of V9 reads: ",formatC(n_reads_V9,big.mark = " ") , "\n")

rm(asv_set_V9)

```

## V4 - protists - DNA

#### All V4

Total numbers of V4 samples:  2928 
Total numbers of V4 ASVs:  55511 
Total numbers of V4 reads:  221 982 399 

##### V4 only protists


Total numbers of V4 samples:  2915 
Total numbers of V4 ASVs:  40039 
Total numbers of V4 reads:  130 393 731 

```{r}

division_memoved <- c("Metazoa", "Fungi", "Streptophyta")

asv_set_V4 <- list()

asv_set_V4$df <- asv_set$df %>% 
  dplyr::filter(gene_region == "V4", 
                DNA_RNA == "DNA",
                !(division %in% division_memoved))

n_reads_pct_V4 <- sum(asv_set_V4$df$n_reads_pct)
n_reads_V4 <- sum(asv_set_V4$df$n_reads)

samples_V4 <- asv_set_V4$df %>% 
  pull("file_code") %>% 
  unique()

n_samples_V4 <- length(samples_V4)
  
asv_code_V4 <- asv_set_V4$df %>% 
  dplyr::filter(gene_region == "V4", 
                DNA_RNA == "DNA",
                !(division %in% division_memoved)) %>% 
  pull("asv_code") %>% 
  unique()

asv_set_V4$fasta <- asv_set$fasta %>% 
  filter(asv_code %in% asv_code_V4)

n_asvs_V4 <- nrow(asv_set_V4$fasta)

cat("Total numbers of V4 samples: ",n_samples_V4, "\n" )
cat("Total numbers of V4 ASVs: ",n_asvs_V4 , "\n")
cat("Total numbers of V4 reads: ", formatC(n_reads_V4,big.mark = " ") , "\n" )
```


## Treemaps (for all)

```{r}

fig_treemap <- asv_set_V4$df %>% 
  treemap(asv_set_V4$fasta, "kingdom", global$supergroup_colors)

fig_treemap <- fig_treemap$g 

```


## Analysis at genus level



### Most abundant genera

```{r}

genus_removed <- "_X|clade|NASSO"

reads <- asv_set_V4$df %>% 
  mutate(n_reads = n_reads_pct/n_reads_pct_V4*100) %>%
  filter(!str_detect(genus, genus_removed)) %>% 
  phyloseq_long_bargraph (n_bars=30, title="", text_scaling = 0.75,
                                   use_asv = FALSE,
                                   taxo_level= genus,
                                   taxo_level_fill = supergroup,
                                   taxo_colors_fill = global$supergroup_color)
 gg_reads <- reads$gg  + 
  ylab("% of total reads") +
  ggtitle("Most abundant genera") 

stations <- asv_set_V4$df %>% 
  select(file_code, supergroup, genus) %>% 
  distinct() %>% 
  group_by(supergroup, genus) %>% 
  count() %>% 
  mutate(n_reads = n/n_samples_V4*100) %>%
  filter(!str_detect(genus, genus_removed)) %>% 
  phyloseq_long_bargraph (n_bars=30, title="", text_scaling = 0.75,
                                   use_asv = FALSE,
                                   taxo_level= genus,
                                   taxo_level_fill = supergroup,
                                   taxo_colors_fill = global$supergroup_color)

gg_stations <- stations$gg + 
  ylab("% of samples where found") +
  ggtitle("Most frequent genera")
  

asvs <- asv_set_V4$df %>% 
  select(asv_code, supergroup, genus) %>% 
  distinct() %>% 
  group_by(supergroup, genus) %>% 
  count() %>% 
  mutate(n_reads = n) %>%
  filter(!str_detect(genus, genus_removed)) %>% 
  phyloseq_long_bargraph (n_bars=30, title="", text_scaling = 0.75,
                                   use_asv = FALSE,
                                   taxo_level= genus,
                                   taxo_level_fill = supergroup,
                                   taxo_colors_fill = global$supergroup_color) 
gg_asvs <- asvs$gg + 
  ylab("Number of ASVs") +
  ggtitle("Genera with most ASVs") 



# --------------------------------------
layout <- "
AACC
AACC
BBDD
BBDD
"


fig_bars_genus <- gg_reads + gg_stations + gg_asvs + guide_area()  +
  plot_layout(guides = "collect", design = layout) +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 30)) 

fig_bars_genus
```


### Correlations

```{r}

genus <- reads$df %>% 
  left_join(rename(stations$df, n_stations = n_reads)) %>% 
    left_join(rename(asvs$df, n_asvs = n_reads)) 

ggplot(data = genus) + 
  geom_point(aes(x=n_asvs, y=n_reads, color = supergroup), size = 3) + 
  scale_x_log10() + scale_y_log10() +
  scale_color_manual(values = global$supergroup_colors)

ggplot(data = genus) + 
  geom_point(aes(x=n_asvs, y=n_stations, color = supergroup), size = 3) + 
  scale_x_log10() + scale_y_log10() +
  scale_color_manual(values = global$supergroup_colors)
```
## Analysis at ASV level

### Most abundant ASV

```{r}

reads <- asv_set_V4$df %>% 
  mutate(n_reads = n_reads_pct/n_reads_pct_V4*100) %>%
  # filter(!str_detect(genus, "_X")) %>% 
  phyloseq_long_bargraph (n_bars=30, title="", text_scaling = 0.75,
                                   use_asv = TRUE,
                                   taxo_level= species,
                                   taxo_level_fill = supergroup,
                                   taxo_colors_fill = global$supergroup_color)
 gg_reads <- reads$gg  + 
  ylab("% of total number of reads") +
  ggtitle("Most abundant ASVs") 
  

# --------------------------------------
  

stations <- asv_set_V4$df %>% 
  select(file_code, kingdom, supergroup, family, species, asv_code) %>% 
  distinct() %>% 
  group_by(kingdom, supergroup, family, species, asv_code) %>% 
  count() %>% 
  mutate(n_reads = n/n_samples_V4*100) %>%
  # filter(!str_detect(genus, "_X")) %>% 
  phyloseq_long_bargraph (n_bars=30, title="", text_scaling = 0.75,
                                   use_asv = TRUE,
                                   taxo_level= genus,
                                   taxo_level_fill = supergroup,
                                   taxo_colors_fill = global$supergroup_color)
gg_stations <- stations$gg + 
  ylab("% of samples where found") +
  ggtitle("Most frequent ASV")  +
  guides(fill = "none")
  

# --------------------------------------

asvs <- reads$df %>% 
  left_join(rename(stations$df, n_stations = n_reads)) 

gg_correl <- ggplot(data = asvs) + 
  geom_point(aes(x=n_stations, y=n_reads, color = supergroup), size = 3) + 
  # scale_x_log10() +
  scale_y_log10(limits = c(0.01, 2)) +
  # ylim(0.01, 2) +
  scale_color_manual(values = global$supergroup_colors) +
  xlab("% of samples where found") +
  ylab("% of total number of reads") +
  # geom_smooth(aes(x=n_stations, y=n_reads), method = "lm") +
  guides(color = "none") +
  theme_bw() +
  ggrepel::geom_text_repel(data = filter(asvs, n_stations > 2), aes(x=n_stations, y=n_reads, label = str_sub(bar_label, 12)))


# --------------------------------------

layout <- "
AACC
AACC
BBDD
BBDD
"


fig_bars_asv <- gg_reads + gg_stations  + gg_correl  + guide_area() +
  plot_layout(guides = "collect", design = layout) +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 30))

fig_bars_asv
```


# Export figures

```{r, eval=TRUE}

ggsave(plot= fig_treemap , filename=path_fig("fig_treemap.pdf"), 
       width = 20 , height = 12, scale=1, units="cm", useDingbats=FALSE) 

ggsave(plot= fig_bars_genus , filename=path_fig("fig_bars_genus.pdf"), 
       width = 16 , height = 12, scale=2.5, units="cm", useDingbats=FALSE)

ggsave(plot= fig_bars_asv , filename=path_fig("fig_bars_asvs.pdf"), 
       width = 18, height = 14, scale=2.5, units="cm", useDingbats=FALSE)





# ggsave(plot= fig_year , filename=path_fig("fig_year.tiff"), 
#        width = 16 , height = 8, scale=1.8, units="cm", compression = "lzw") 


```


