---
title: "MetaPR2 - Map"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


# Initialize

```{r init, echo=TRUE, message=FALSE, warning=FALSE}
source(here::here("R", "init.R"))
```

# Figures

## Map of all samples for which we have coordinates

```{r fig.height=8, fig.width=12}

asv_summary <- asv_set$df %>%  
      distinct(project, dataset_id, longitude, latitude) %>% 
      mutate(project =  case_when(str_detect(project, "OSD") ~ "OSD",
                                  str_detect(project, "Tara") ~ "Tara",
                                  str_detect(project, "Malaspina") ~ "Malaspina",
                                  TRUE ~ "Other")) %>% 
      mutate(project = forcats::fct_relevel(project, c("OSD", "Tara","Malaspina", "Other")))

n_datasets = length(unique(asv_summary$dataset_id))

# Using world map

  # world <- map_data("world")
  # 
  # fig_map_stations <- ggplot() + 
  #   geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="grey") +
  #   coord_fixed(1.3) +
  #   # coord_map("mollweide") +
  #   geom_point(data=asv_summary, aes(x=longitude, y=latitude, color = project), size=2.5) + 
  #   scale_color_viridis_d(option = "magma") +
  #   labs(title = str_c("Map fo samples for ", n_datasets," datasets.") ,
  #        colors = "Project",
  #        x = "Longitude",
  #        y = "Latitude") +
  #   scale_x_continuous(breaks = (-4:4) * 45) +
  #   scale_y_continuous(breaks = (-2:2) * 30)
  # 
  # print(fig_map_stations)
  
# Using sf - Nicer for scales....
  
  # See for removing lines : https://stackoverflow.com/questions/49836184/cant-remove-gridlines-when-plotting-with-geom-sf
    

  world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
  
  # Next line is to have the grid lines: see https://stackoverflow.com/questions/68343004/ggplot-and-geom-sf-not-showing-graticule-and-tick-marks-on-world-map
  sf::sf_use_s2(FALSE)
  
  crs_longlat <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
  crs_robinson = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs"
  
  asv_summary_sf <- asv_summary %>% 
    filter(!is.na(longitude)) %>% 
    sf::st_as_sf( coords = c("longitude", "latitude"),
                crs = crs_longlat) 
  
  # boundary <- sf::st_multilinestring(list(rbind(c(-180,90), c(180,90)), rbind(c(180,-90), c(-180,-90))))
  # boundary <- sf::st_sfc(boundary, crs=crs_longlat)
  # boundary <- sf::st_sf(geometry = boundary)

  fig_map_stations <- ggplot() + 
    geom_sf(data = world, color="grey60", fill="grey60")  +
    geom_sf(data=asv_summary_sf, aes(color=project), size=1.5) +
    # geom_sf(data=boundary)+ 
    theme_bw() +
    # theme(panel.border=element_blank()
    #       # panel.grid = element_line(colour = "grey90", size=3)
    #       # axis.text.x= element_blank(),
    #       # axis.text.y = element_blank()
    #       # plot.margin=margin(0,0,0,0),
    #       # aspect.ratio = 0.5
    #       )  +
    scale_color_viridis_d(option = "plasma", begin = 0, end = 0.85, direction = -1) +
    # scale_color_brewer(palette = "Set2") + # https://www.datanovia.com/en/fr/blog/top-palettes-de-couleurs-r-a-connaitre-pour-une-meilleur-visualisation-des-donnees/
    labs(
         # title = str_c("Map of samples for ", n_datasets," datasets.") ,
         color = "Project",
         x = "",
         y = "") +
    scale_x_continuous(breaks = seq(from = -180, to = 180, by = 60)) +
    # scale_y_continuous(breaks=c(-89.999, 89.999)) +
    scale_y_continuous(breaks=seq(from = -90, to = 90, by = 30)) +
    coord_sf(crs = crs_longlat, expand =FALSE)
    # coord_sf(crs = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs", expand = TRUE) 
  
  fig_map_stations
```

# Export figures

```{r, eval=TRUE}

ggsave(plot= fig_map_stations , filename=path_fig("fig_map_stations.pdf"), 
       width = 18, height = 10, scale=1.5, units="cm", useDingbats=FALSE) 


```