---
title: "MetaPR2 - maps"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---

# Initialize

```{r, echo=TRUE, message=FALSE, warning=FALSE}
   # library(pr2database)
   library(stringr)
   library(ggplot2)
   library(dplyr)
   library(tidyr)
   library(tibble)
   library(readr)
   library(maps)
   library(readxl)
   library(rio) # for import/export of data

   if(any(grepl("package:dvutils", search()))) detach("package:dvutils", unload=TRUE)
   library("dvutils")

   # data("pr2")
```


# Read the metaPR2 tables

```{r}
  db_con <- db_connect(db_info("metapr2_google"))
  datasets <- tbl(db_con, "metapr2_datasets") %>% collect()
  metadata <- tbl(db_con, "metapr2_metadata") %>% collect()
  samples <- tbl(db_con, "metapr2_samples") %>% collect()
  db_disconnect(db_con)
  
  
  metapr2 <- samples %>% 
    left_join(metadata) %>% 
    left_join(datasets)
  
```

## Filters to keep specific datasets

### Only public

```{r}
datasets_published <- datasets %>% 
  filter(!is.na(paper_doi),
         !str_detect(ecosystem,"agriculture|terrestrial|freshwater"),
         !((gene == "16S rRNA") & is.na(organelle))    # Remove 16S studies not targetting plastid
         )

 datasets_published_18S <- datasets_published %>% 
  filter(str_detect(gene,"18S"))
   
```

### TaxMarc

```{r}

datasets_TM <- datasets %>% 
  filter(str_detect(dataset_code, "AWI|MicroPolar")) 


   
```

```{r}
 samples <- metapr2 %>% 
  filter(dataset_id %in% c(datasets_TM$dataset_id,datasets_published_18S$dataset_id))
```


# Figures

```{r}
theme_set(theme_bw())
```


## Map of all samples for which we have coordinates

```{r fig.height=12, fig.width=12}

asv_summary <- samples %>%  
      distinct(project, dataset_id, longitude, latitude) %>% 
      mutate(project =  case_when(str_detect(project, "AWI") ~ "AWI",
                                  str_detect(project, "MicroPolar") ~ "MicroPolar",
                                  TRUE ~ "Other")) %>% 
      mutate(project = forcats::fct_relevel(project, c("MicroPolar", "AWI", "Other")))

n_datasets = length(unique(asv_summary$dataset_id))

# Using world map

  world <- map_data("world")
  
  fig_map_stations <- ggplot() + 
    geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="grey") +
    coord_fixed(1.3) +
    # coord_map("mollweide") +
    geom_point(data=asv_summary, aes(x=longitude, y=latitude, color = project), size=2.5) + 
    scale_color_manual(values = c("blue", "red", "black")) +
    # scale_color_viridis_d(option = "magma") +
    labs(title = str_c("Map fo samples for ", n_datasets," datasets.") ,
         colors = "Project",
         x = "Longitude",
         y = "Latitude") +
    scale_x_continuous(breaks = (-4:4) * 45) +
    scale_y_continuous(breaks = (-2:2) * 30)
  
  
  
  print(fig_map_stations)
  
  fig_map_stations_polar <- fig_map_stations  +
  coord_map("ortho", orientation=c(75, -20, 0), ylim=c(60,90))+
  scale_y_continuous(breaks = (12:18) * 5) +
  scale_x_continuous(breaks = (-3:3) * 60) +
  xlab("") + ylab("") +
  # theme_void() +
  theme(axis.line=element_blank(),
  axis.text.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks=element_blank(),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  # legend.position="none",
  panel.background=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_line(color="grey35"),
  panel.grid.minor=element_blank(),
  plot.background=element_blank())+
  labs(tag="")
  
  fig_map_stations_polar

  
# Using sf
  
  # See for removing lines : https://stackoverflow.com/questions/49836184/cant-remove-gridlines-when-plotting-with-geom-sf
    

  world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
  
  crs_longlat <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
  crs_robinson = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs"
  
  asv_summary_sf <- asv_summary %>% 
    filter(!is.na(longitude)) %>% 
    sf::st_as_sf( coords = c("longitude", "latitude"),
                crs = crs_longlat) 
  
  # boundary <- sf::st_multilinestring(list(rbind(c(-180,90), c(180,90)), rbind(c(180,-90), c(-180,-90))))
  # boundary <- sf::st_sfc(boundary, crs=crs_longlat)
  # boundary <- sf::st_sf(geometry = boundary)

  fig_map_stations <- ggplot() + 
    geom_sf(data = world, color="grey70", fill="grey70")  +
    geom_sf(data=asv_summary_sf, aes(color=project), size=2.5) +
    # geom_sf(data=boundary) +
    theme(panel.border=element_blank(),
          panel.grid = element_line(colour = "grey70", size=2),
          axis.text.x= element_blank(),
          axis.text.y = element_blank()
          # plot.margin=margin(0,0,0,0),
          # aspect.ratio = 0.5
          ) + 
    scale_color_viridis_d(option = "viridis") +
    # scale_color_brewer() +
    labs(
         # title = str_c("Map of samples for ", n_datasets," datasets.") ,
         color = "Project",
         x = "",
         y = "") +
    scale_x_continuous(breaks = c(-180, 180)) +
    scale_y_continuous(breaks=c(-89.999, 89.999)) +
    coord_sf(crs = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m no_defs", expand = TRUE) 
  
  print(fig_map_stations)
  
```

